### ISSUE TITLE
kernel panic when unmounting a folder (reproducible)

### ISSUE THREAD

**Issue by mehdisebbar** [osxfuse/sshfs#11]
Hi,

every time I unmount a folder, I get a kernel panic, EVEN if the folder is not mounted.

Installed with brew, on OSX Yosemite

command: 
➜  ~  sshfs -unmount @server:/ mounttmp

➜  ~  sshfs -V
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.3.8

Stacktrace:

Mon Mar  2 01:34:46 2015

*** Panic Report ***
panic(cpu 2 caller 0xffffff801721a46e): Kernel trap at 0xffffff80173443e8, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00000000000000c0, CR3: 0x0000000335ab20cb, CR4: 0x00000000001627e0
RAX: 0xffffff803bf51580, RBX: 0xffffff80368c0c00, RCX: 0x0000000003000000, RDX: 0xffffff80368904e0
RSP: 0xffffff81ffba3ac0, RBP: 0xffffff81ffba3ae0, RSI: 0x0000000000000020, RDI: 0xffffff80368904e0
R8:  0xffffff8037265840, R9:  0x0000000000000000, R10: 0xffffff8048fde000, R11: 0x0000000000000000
R12: 0x00000000000000c0, R13: 0xffffff80413d7800, R14: 0x0000000000000000, R15: 0x0000000000000020
RFL: 0x0000000000010286, RIP: 0xffffff80173443e8, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00000000000000c0, Error code: 0x0000000000000000, Fault CPU: 0x2

Backtrace (CPU 2), Frame : Return Address
0xffffff81ffba3770 : 0xffffff801712fe41 
0xffffff81ffba37f0 : 0xffffff801721a46e 
0xffffff81ffba39b0 : 0xffffff8017236683 
0xffffff81ffba39d0 : 0xffffff80173443e8 
0xffffff81ffba3ae0 : 0xffffff7f9982bb40 
0xffffff81ffba3b30 : 0xffffff80173823d9 
0xffffff81ffba3b80 : 0xffffff8017370cb6 
0xffffff81ffba3c10 : 0xffffff8017365b53 
0xffffff81ffba3e00 : 0xffffff80175ae26b 
0xffffff81ffba3e30 : 0xffffff80175ed214 
0xffffff81ffba3f50 : 0xffffff801764b386 
0xffffff81ffba3fb0 : 0xffffff8017236e86 
      Kernel Extensions in backtrace:
         com.github.osxfuse.filesystems.osxfusefs(2.3.8)[6AC3DE62-14A4-3895-A6A4-E3253A0B00F3]@0xffffff7f9982b000->0xffffff7f99840fff

BSD process name corresponding to current thread: sshfs

Mac OS version:
14C109

Kernel version:
Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64
Kernel UUID: DCF5C2D5-16AE-37F5-B2BE-ED127048DFF5
Kernel slide:     0x0000000016e00000
Kernel text base: 0xffffff8017000000
__HIB  text base: 0xffffff8016f00000
System model name: MacBookPro11,2 (Mac-3CBD00234E554E41)

System uptime in nanoseconds: 218076534539
last loaded kext at 208269146273: com.github.osxfuse.filesystems.osxfusefs  2.3.8 (addr 0xffffff7f9982b000, size 90112)
last unloaded kext at 111271460461: com.apple.driver.AppleFileSystemDriver  3.0.1 (addr 0xffffff7f99632000, size 8192)
loaded kexts:
com.github.osxfuse.filesystems.osxfusefs    2.3.8
org.virtualbox.kext.VBoxNetAdp  4.3.22
org.virtualbox.kext.VBoxNetFlt  4.3.22
org.virtualbox.kext.VBoxUSB 4.3.22
org.virtualbox.kext.VBoxDrv 4.3.22
com.intel.kext.intelhaxm    1.1.1
com.apple.driver.AudioAUUC  1.70
com.apple.iokit.IOBluetoothSerialManager    4.3.2f6
com.apple.filesystems.autofs    3.0
com.apple.driver.AGPM   100.15.5
com.apple.driver.ApplePlatformEnabler   2.1.7d1
com.apple.driver.X86PlatformShim    1.0.0
com.apple.driver.AppleOSXWatchdog   1
com.apple.driver.AppleGraphicsDevicePolicy  3.7.7
com.apple.driver.AppleUpstreamUserClient    3.6.1
com.apple.driver.AppleIntelHD5000Graphics   10.0.2
com.apple.driver.AppleHDA   269.25
com.apple.driver.AppleBacklight 170.5.0
com.apple.iokit.IOUserEthernet  1.0.1
com.apple.driver.AppleMCCSControl   1.2.11
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport 4.3.2f6
com.apple.driver.AppleIntelFramebufferAzul  10.0.2
com.apple.Dont_Steal_Mac_OS_X   7.0.0
com.apple.driver.AppleHWAccess  1
com.apple.driver.AppleHV    1
com.apple.driver.AppleCameraInterface   5.29.0
com.apple.driver.AppleLPC   1.7.3
com.apple.driver.AppleSMCLMU    2.0.7d0
com.apple.driver.AppleThunderboltIP 2.0.2
com.apple.driver.AppleUSBTCButtons  240.2
com.apple.driver.AppleUSBTCKeyboard 240.2
com.apple.driver.AppleUSBCardReader 3.5.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0d1
com.apple.BootCache 35
com.apple.driver.AppleUSBHub    705.4.2
com.apple.driver.XsanFilter 404
com.apple.iokit.IOAHCIBlockStorage  2.7.0
com.apple.driver.AppleAHCIPort  3.1.0
com.apple.driver.AirPort.Brcm4360   910.26.12
com.apple.driver.AppleUSBXHCI   710.4.11
com.apple.driver.AppleSmartBatteryManager   161.0.0
com.apple.driver.AppleRTC   2.0
com.apple.driver.AppleACPIButtons   3.1
com.apple.driver.AppleHPET  1.8
com.apple.driver.AppleSMBIOS    2.1
com.apple.driver.AppleACPIEC    3.1
com.apple.driver.AppleAPIC  1.7
com.apple.nke.applicationfirewall   161
com.apple.security.quarantine   3
com.apple.security.TMSafetyNet  8
com.apple.iokit.IOSerialFamily  11
com.apple.kext.triggers 1.0
com.apple.driver.DspFuncLib 269.25
com.apple.kext.OSvKernDSPLib    1.15
com.apple.iokit.IOSurface   97
com.apple.driver.AppleSMBusController   1.0.13d1
com.apple.iokit.IOBluetoothHostControllerUSBTransport   4.3.2f6
com.apple.iokit.IOBluetoothFamily   4.3.2f6
com.apple.AppleGraphicsDeviceControl    3.8.6
com.apple.iokit.IOAcceleratorFamily2    156.6
com.apple.driver.X86PlatformPlugin  1.0.0
com.apple.iokit.IOUSBUserClient 705.4.0
com.apple.driver.IOPlatformPluginFamily 5.8.1d38
com.apple.driver.AppleBacklightExpert   1.1.0
com.apple.iokit.IONDRVSupport   2.4.1
com.apple.driver.AppleGraphicsControl   3.8.6
com.apple.driver.AppleHDAController 269.25
com.apple.iokit.IOHDAFamily 269.25
com.apple.iokit.IOAudioFamily   203.3
com.apple.vecLib.kext   1.2.0
com.apple.driver.AppleSMC   3.1.9
com.apple.iokit.IOGraphicsFamily    2.4.1
com.apple.driver.AppleUSBMultitouch 245.2
com.apple.iokit.IOUSBHIDDriver  705.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice   3.7.3
com.apple.iokit.IOUSBMassStorageClass   3.7.1
com.apple.iokit.IOSCSIArchitectureModelFamily   3.7.3
com.apple.driver.AppleUSBMergeNub   705.4.0
com.apple.driver.AppleUSBComposite  705.4.9
com.apple.driver.AppleThunderboltDPInAdapter    4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily    4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter 2.0.2
com.apple.iokit.IOAHCIFamily    2.7.5
com.apple.driver.AppleThunderboltNHI    3.1.7
com.apple.iokit.IOThunderboltFamily 4.2.1
com.apple.iokit.IO80211Family   710.55
com.apple.driver.mDNSOffloadUserClient  1.0.1b8
com.apple.iokit.IONetworkingFamily  3.2
com.apple.iokit.IOUSBFamily 710.4.14
com.apple.driver.AppleEFINVRAM  2.0
com.apple.iokit.IOHIDFamily 2.0.0
com.apple.driver.AppleEFIRuntime    2.0
com.apple.iokit.IOSMBusFamily   1.1
com.apple.security.sandbox  300.0
com.apple.kext.AppleMatch   1.0.0d1
com.apple.driver.AppleKeyStore  2
com.apple.driver.AppleMobileFileIntegrity   1.0.5
com.apple.driver.AppleCredentialManager 1.0
com.apple.driver.DiskImages 396
com.apple.iokit.IOStorageFamily 2.0
com.apple.iokit.IOReportFamily  31
com.apple.driver.AppleFDEKeyStore   28.30
com.apple.driver.AppleACPIPlatform  3.1
com.apple.iokit.IOPCIFamily 2.9
com.apple.iokit.IOACPIFamily    1.4
com.apple.kec.corecrypto    1.0
com.apple.kec.Libm  1
com.apple.kec.pthread   1
Model: MacBookPro11,2, BootROM MBP112.0138.B14, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.18f15
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.159.13.12)
Bluetooth: Version 4.3.2f6 15235, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

Thanks for your help :)

**Comment by bfleischer** [comment]
FUSE volumes should be unmounted using the `umount /path/to/mountpoint` command. There is no "-unmount" option in sshfs. See the man page for details.

In addition to that, the osxfuse version you are using is very outdated and does not even support Yosemite. It is more than three years old. Please upgrade to osxfuse 2.7.5, which is the latest version as of writing this and reopen the ticket if you are still seeing kernel panics.
