### ISSUE TITLE
Compiling static binary fails with "Undefined symbols for architecture x86_64"

### ISSUE THREAD

**Issue by rteslaru** [osxfuse/sshfs#16]
Hi,

Would it be possible to provide instructions on how to re-create the statically linked binary, starting from the source code in this repository? 

I am trying to follow the instructions from https://groups.google.com/d/msg/osxfuse-group/xhWB-Pbk56M/XQbIC3hy8kQJ, but I get the following results:

```
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "_darwin_sem_destroy", referenced from:
      _sftp_request_wait in sshfs-sshfs.o
      _process_requests in sshfs-sshfs.o
      _clean_req in sshfs-sshfs.o
  "_darwin_sem_init", referenced from:
      _sftp_request_send in sshfs-sshfs.o
  "_darwin_sem_post", referenced from:
      _process_requests in sshfs-sshfs.o
      _clean_req in sshfs-sshfs.o
  "_darwin_sem_wait", referenced from:
      _sftp_request_wait in sshfs-sshfs.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

FWIW, I have the following ports installed via macports, as well as OSXFUSE 2.8.2:

```
  expat @2.1.0_0 (active) platform='darwin 14' archs='x86_64'
  gettext @0.19.6_0 (active) platform='darwin 14' archs='x86_64'
  glib2-devel @2.45.2_1 (active) platform='darwin 14' archs='x86_64'
  libffi @3.2.1_0 (active) platform='darwin 14' archs='x86_64'
  libiconv @1.14_0 (active) platform='darwin 14' archs='x86_64'
  ncurses @6.0_0 (active) platform='darwin 14' archs='x86_64'
  zlib @1.2.8_0 (active) platform='darwin 14' archs='x86_64'
```

Would appreciate any hints as to where to start looking for a solution.

Thanks!

**Comment by rteslaru** [comment]
Still struggling with this, would be great if anyone had any thoughts on what to try next. As mentioned, I tried following the instructions from https://groups.google.com/d/msg/osxfuse-group/xhWB-Pbk56M/XQbIC3hy8kQJ -- didn't work (error message above).

**Comment by bfleischer** [comment]
The `gcc` command in the Google Group message you referenced is outdated. I use the following command sequence to build a universal sshfs binary (i386, x86_64, ppc, ppc64) on Mac OS X 10.5:

    autoreconf -i
    CFLAGS="-arch i386 -arch x86_64 -arch ppc -arch ppc64 -I/usr/local/include/osxfuse" ./configure --prefix=/usr/local --disable-dependency-tracking
    make
    gcc -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -D_REENTRANT -I/usr/local/include/osxfuse/fuse -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include  -arch i386 -arch x86_64 -arch ppc -arch ppc64 -I/usr/local/include/osxfuse -Wall -W -I./compat   -o sshfs sshfs-sshfs.o sshfs-cache.o  compat/sshfs-darwin_compat.o -L/usr/local/lib -losxfuse -pthread /opt/local/lib/libiconv.a /opt/local/lib/libgthread-2.0.a /opt/local/lib/libglib-2.0.a /opt/local/lib/libintl.a -framework Carbon
