### ISSUE TITLE
GLib-CRITICAL error

### ISSUE THREAD

**Issue by knowledgecode** [osxfuse/sshfs#17]
Hi,
I'm using `sshfs` which is installed from a source package (`osxfuse-sshfs-2.5.0.tar.gz`) on Mac OS X 10.10. It has been displayed the following error message since I've updated `glib` from 2.44.1 to 2.46.0:
```
$ sshfs -V

(process:5226): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.8.2
no mount point
```
It seems the error is caused by the following line in `sshfs.c`:
```
3954:
3955:   /* Until this gets fixed somewhere else. */
3956:   g_slice_set_config(G_SLICE_CONFIG_ALWAYS_MALLOC, TRUE);
3957:#endif /* __APPLE__ */
```
Also a compiler warns at this line:
```
sshfs.c:3956:2: warning: 'g_slice_set_config' is deprecated [-Wdeprecated-declarations]
        g_slice_set_config(G_SLICE_CONFIG_ALWAYS_MALLOC, TRUE);
```
I don't know very much about neither `sshfs` nor `glib`. What should I use instead of this function? Or, can I remove this line?

**Comment by Joseffb** [comment]
GSLICE=always-malloc
Use environment setting?

**Comment by knowledgecode** [comment]
Thank you for the advice.
I tried the environment setting, but the value of `slice_config.always_malloc` has remained `0` (debugged with printf).

I added the following line in my `.bash_profile`:
```
export G_SLICE=always-malloc
```
And then removed the function (`g_slice_set_config`). Consequently, the error message has not been displayed, but it doesn't mean the issue has been fixed.

Do you have any other idea? Is this a bug of `glib` 2.46?

**Comment by Joseffb** [comment]
No problem.

Not a bug per say as it was giving you a warning that a method is no longer supported (aka deprecated). The new method for doing what that was supposed to do is to set it up as an environment setting as you did.

I’ll leave it to the develops on this project to figure out longer term solution.

**Comment by knowledgecode** [comment]
I got it. Thank you!

**Comment by vasi** [comment]
Do we have any any what the original problem was? Why is/was G_SLICE_CONFIG_ALWAYS_MALLOC necessary on OS X?

I tried to track this down in the history, but it was in the original sshfs patch from Amit Singh—there's no more detail on why it's here.

**Comment by bfleischer** [comment]
I have not been able to find out why `G_SLICE_CONFIG_ALWAYS_MALLOC`  has been set before but removing the `g_slice_set_config()` call does not seem to have any negative side effects.
