### ISSUE TITLE
SSHFS should auto-create mount points

### ISSUE THREAD

**Issue by eladts** [osxfuse/sshfs#27]
Since macOS Sierra, one needs root privileges to create mount points in /Volumes. OSXFUSE 3.5.0 introduced a mechanism for OSXFUSE to create mount points, however SSHFS doesn't use it (see [OSXFUSE issue #306](https://github.com/osxfuse/osxfuse/issues/306)). Please add this feature to SSHFS to restore the ability to mount in /Volumes without root privileges.

Thanks!

**Comment by mischievous** [comment]
I have a fix for this I only issue right now if that I don't have a static version of glib2.0 to compile against and test with.  Also last time I tried to check something into github I had nothing but problems.  Is there a steps by step guide some where?

**Comment by bfleischer** [comment]
The issue should be fixed in commit f187961c7a6a2433c8af7e758d8185568d8006a2.
