### ISSUE TITLE
unable handle several requests at the same time

### ISSUE THREAD

**Issue by jolan78** [osxfuse/sshfs#3]
SSHFS us supposed to support "Multithreading: more than one request can be on it's way to the server" , according to http://fuse.sourceforge.net/sshfs.html.
I no not think that osxfuse / sshfs allow such thing.
this testcase for instance seems to demonstrate that concurrent requests do not work : 
- open a server with sshfs
- copy a large file to the server
- while the file is uploading, connect to a second server

expected result : the second server mounts and a second upload is possible while the first is not finished.

actual result : the second server do not mount until the first upload is finished.

MacOS 10.7.5
SSHFS version 2.4 (OSXFUSE SSHFS 2.4.1)
OSXFUSE library version: FUSE 2.7.3 / OSXFUSE 2.5.4
volumes are mounted with these options : -olocal,auto_cache,reconnect,compression=yes,volname=XXXX

**Comment by bfleischer** [comment]
Please reopen the ticket if this is still an issue with sshfs 2.5.0.
