### ISSUE TITLE
fusermount not installed

### ISSUE THREAD

**Issue by dportabella** [osxfuse/sshfs#31]
I installed both packages:
https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.5.3/osxfuse-3.5.3.dmg
https://github.com/osxfuse/sshfs/releases/download/osxfuse-sshfs-2.5.0/sshfs-2.5.0.pkg

and `sshfs` works; that's great!
however the command `fusermount` is not installed.

**Comment by bfleischer** [comment]
`fusermount` does not exist on macOS. You can unmount FUSE volume by running `umount /path/to/mountpoint` in Terminal or pressing the eject button in Finder.

**Comment by dportabella** [comment]
ok, thx.
please update the README.md accordingly (it currently mentions fusermount).

**Comment by ggarek** [comment]
Man pages also state to use `fusermount` and there is no word about `umount`. It may be worth updating as well.

```
NAME
       SSHFS - filesystem client based on ssh

SYNOPSIS
   mounting
       sshfs [user@]host:[dir] mountpoint [options]

   unmounting
       fusermount -u mountpoint
```

```
➜ sshfs --version
SSHFS version 2.10
OSXFUSE 3.10.2
FUSE library version: 2.9.7
fuse: no mount point
```
