### ISSUE TITLE
SSHFS slow

### ISSUE THREAD

**Issue by guardiande** [osxfuse/sshfs#33]
Hi,

sshfs mounts operate slowly on OS X. Compared to a Linux sshfs mount the speeds are much slower: 10 MB/s on Linux and about 800 KB/s on OS X. I'm running the most recent version of OSXFUSE (3.5.4) and SSHFS (2.5.0 from OSXFUSE and 2.8.0 from Homebrew).

Tuning the I/O options (iosize, readahed, max_read) did not help. Debugging shows that the sshfs on OS X only uses a 4K reads whereas Linux uses 128K reads. I guess that's where the difference in throughput comes from.

The client is a Sierra MacBook Pro and the server is an Ubuntu 16.04.1.

**Comment by guardiande** [comment]
I just tried the same on OS X but not over Wifi but over an USB ethernet adapter. The I/O size sticks to 4096 bytes but the speed is much higher, similar to the ethernet based Linux speeds.

But I still think to remember that the speeds over Wifi used to be much higher and I expect the speed to increase when the I/O size is bigger.

Any idea how to tune the read size?

**Comment by bfleischer** [comment]
The issue should be fixed in commit 5c0dbfe3eb40100f9277e863926f2e7d7c9a5a4c.
