### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by diktomat** [osxfuse/sshfs#43]
```
# sshfs --version
2017
SSHFS version 2.10
OSXFUSE 3.7.1
FUSE library version: 2.9.7
```

I use sshfs to mount my media drive (~1.2TB used of 2TB, ext4) to my Macbook, from a Raspberry Pi used as NAS. When freshly mounted, sshfs uses less than a MB of RAM, but with time, the usage grows. Yesterday, after wondering why my hard drive was full, I detected that /var/vm was 38GB big, Activity Monitor showed a swap usage of these 38GB, and memory use of sshfs was shown as 36GB. I unmounted, mounted again, and after playing a bit of music and a short video off the mounted drive, usage was nearly a GB again, growing ever since.

**Comment by UmutAlihan** [comment]
same issue here

**Comment by bfleischer** [comment]
Please raise the issue in the https://github.com/libfuse/sshfs issue tracker. I don't think FUSE for macOS is to blame for this.
