### ISSUE TITLE
Update to newer libfuse/sshfs?

### ISSUE THREAD

**Issue by dgonyier** [osxfuse/sshfs#45]
Current is 3.3.2. (https://github.com/libfuse/sshfs) Is there a reason for sticking with SSHFS 2.5.0 for OSXFUSE?

Thanks.

**Comment by ghost** [comment]
Up please !

**Comment by poetaman** [comment]
@bfleischer  Now its 3.7.2, and the binary is PowerPC+Intel instead of AppleSilicon+Intel.

**Comment by bfleischer** [comment]
sshfs 3.x requires libfuse 3, but macFUSE ships with libfuse 2. Until libfuse 3 has been ported to macOS we are stuck with sshfs 2.x on macOS. As of writing this the latest version of sshfs that will run on macOS is version 2.10 which is serveral years old but works just fine as far as I can tell. A universal sshfs 2.10 build (Apple silicon and Intel) can be downloaded from https://macfuse.io/.

macOS specific changes from this repository have been merged into the upstream repository https://github.com/libfuse/sshfs years ago. Future development will continue there.
