### ISSUE TITLE
Not compatible with macOS Catalina

### ISSUE THREAD

**Issue by sjquon** [osxfuse/sshfs#53]
The current version is not compatible with the new macOS. Will a new version be released soon?

**Comment by bfleischer** [comment]
What doesn't work?

**Comment by mischievous** [comment]
Its working as expected for me.

**Comment by sjquon** [comment]
I get an error message that the installed version of FUSE is too old for the operating system.

**Comment by mischievous** [comment]
I have 3.10.3 on my system.

**Comment by bfleischer** [comment]
Version 3.10.3 of FUSE for macOS works fine on Catalina.

@sjquon Download and install the latest version of FUSE from https://osxfuse.github.io.

**Comment by sjquon** [comment]
Thanks! I was mistaken. I just updated the FUSE package and it works now.

**Comment by bfleischer** [comment]
Great!

**Comment by ghoshaw** [comment]
@sourcejedi , How to update the FUSE package? I still get an error message that the installed version of FUSE is too old for the operating system.
