### ISSUE TITLE
Fuse 3.10.4 not working with MacOS Catalina

### ISSUE THREAD

**Issue by knowledgelist** [osxfuse/sshfs#54]
I am getting the following error when trying to launch sshfs via fuse:

```
(process:807): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Cannot load kext from /opt/local/Library/Extensions/fuse4x.kext
fuse4x kernel extension was not loaded. Please check /var/log/{system|kernel|debug}.log for more information.
```

**Comment by bfleischer** [comment]
fuse4x is an old FUSE fork. You are not using FUSE for macOS (aka osxfuse). You need to install a version of SSHFS that uses FUSE for macOS instead of Fuse4X.

**Comment by knowledgelist** [comment]
Thanks! I am a newbie, can you please share the link for the version of SSHFS which uses FUSE for macOS. And how do I uninstall SSHFS which uses Fuse4x
