### ISSUE TITLE
MacFuse 4.2.1 works on Big Sur 11.6 perfectly! None work on Monterey beta5 or Later.

### ISSUE THREAD

**Issue by castiellian** [osxfuse/sshfs#70]
**This is how I make Big Sur to works:**

### **1. disable sip**

csrutil disable && csrutil authenticated-root disable
csrutil status
csrutil authenticated-root status

### **2. install homebrew**

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

### **3. install ntfs-3g**

vi `brew formula ntfs-3g`
search ：/on_mac do
find out this：
     ` on_macos do`
       `disable! date: "2021-04-08", because: "requires closed-source macFUSE"`
       `end`
disable limitation：
       `# on_macos do`
      `# disable! date: "2021-04-08", because: "requires closed-source macFUSE"`
     ` # end`
：/x save

install CLI 13 before build ntfs-3g from source code

sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
install Command Line Tools for Xcode 13.0
brew install curl  
brew install --build-from-source ntfs-3g

### **4. modify mount_ntfs**
diskutil list，

#:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk0
   1:       Microsoft Basic Data soft                    1.0 TB     disk0s1

sudo diskutil unmount /dev/disk0s1
sudo mkdir ～/test
sudo /usr/local/bin/ntfs-3g /dev/disk0s1 ～/test -o local -o allow_other -o auto_xattr -o auto_cache
or
sudo /usr/local/sbin/mount_ntfs /dev/disk0s1 ～/test
then
sudo diskutil list
/dev/disk6 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +1.0 TB     disk6
                                 Physical Store disk1s2
   1:                APFS Volume ⁨MacOS Big Sur - 数据⁩    121.7 GB   disk6s1
   2:                APFS Volume ⁨Preboot⁩                 355.1 MB   disk6s2
   3:                APFS Volume ⁨Recovery⁩                622.8 MB   disk6s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk6s4
   5:                APFS Volume ⁨MacOS Big Sur⁩           15.3 GB    disk6s5
   6:              APFS Snapshot ⁨com.apple.bless.62DB...⁩ 15.3 GB    disk6s5s1
sudo diskutil unmount /dev/disk6s5
sudo mkdir ～/BigSurRW
sudo mount -o nobrowse -t apfs /dev/disk6s5 ～/BigSurRW
cd ~/BigSurRW/sbin
sudo mv mount_ntfs mount_ntfs.apple.orig
sudo ln -s /usr/local/sbin/mount_ntfs /sbin/mount_ntfs
or
touch mount_ntfs && nano mount_ntfs
paste：
`################################`
`#!/bin/sh`
`# fall back to the apple version if ntfs-3g is gone.`
`if [ -x /usr/local/sbin/mount_ntfs ]; then`
  `exec /usr/local/sbin/mount_ntfs "$@"`
`else`
 `exec /sbin/mount_ntfs.apple.orig "$@"`
`fi`
`################################`
chmod +x mount_ntfs

### **5. Create new snapshot for Big Sur** 

sudo bless —folder /Users/xxx/BigSurRW/System/Library/CoreServices —bootefi —create-snapshot
and reboot  to Recovery

### **6. Enable SIP:**
csrutil enable&& csrutil authenticated-root enable

**Comment by eengstrom** [comment]
Under MacOS Monterey, none of this is necessary. Installation of the latest (4.2.4) version of MacFuse works fine, excepting you have to allow kernel extensions in the security policy through recovery mode.

You do **not** need to disable SIP, nor is that advisable.

I suggest this issue be closed.
