### ISSUE TITLE
Problem write apple file

### ISSUE THREAD

**Issue by tetesh** [osxfuse/sshfs#74]
Hi I'm mounting a user's home directory on MacOs
`sudo /usr/local/bin/sshfs -o uid=1015390 -o gid=4222 -o allow_other  testuser@10.x.x.x: /Users/testuser -p 2121`
command works out successfully:
```
mount | grep macfuse
testlifford@10.21.50.19: on /Users/testlifford (macfuse, synchronous)
```
But when logging in, mac cannot write files to this folder.. I think this is due to the fact that imac cannot write its extended attributes

**Comment by bfleischer** [comment]
Most permission issues go away when using the mount time option defer_permission. For details see https://github.com/macfuse/macfuse/wiki/Mount-Options#default_permissions-and-defer_permissions.
