### ISSUE TITLE
Any way to mount a remote as the internal drive?

### ISSUE THREAD

**Issue by mrdc** [osxfuse/sshfs#76]
Hello,

Are there any way to mount a remote as the internal drive? So, it can be seen in Locations in Finder and accessed by a software, which looks for internal drives only.

**Comment by bfleischer** [comment]
You can mount the volume with the local option: `-o local`. macOS will treat the volume as local. This means the volume is expected to be very responsive and more file system requests will be issued. I don't recommend using this option if you network connection to the server is not great. Please see https://github.com/macfuse/macfuse/wiki/Mount-Options#local.
