### ISSUE TITLE
Creation date always as epoch with sshfs [MacOS >= 10.14.5]

### ISSUE THREAD

**Issue by nedex** [osxfuse/sshfs#77]
This is the same issue I've reported on osxfuse/osxfuse:
https://github.com/osxfuse/osxfuse/issues/623

Basically, any file in a ssh mounted directory will always have epoch as creation date (1/1/1970).

Is there a way to fix this or is it an os limitation?

Thank you!

**Comment by bfleischer** [comment]
Closed. Please see my reply in https://github.com/osxfuse/osxfuse/issues/623.
