### ISSUE TITLE
[New Feature Required] 

### ISSUE THREAD

**Issue by CreatorZZY** [osxfuse/sshfs#80]
When Close Display and reopen, ssh disconnect and make a judgment of network connection and then umount sshfs automately. Or just reconnect when network is available.

I find no reconnection when i reopened my macbook's display, and the Finder Crashed.

**Comment by bfleischer** [comment]
macOS specific changes from this repository have been merged into the upstream repository https://github.com/libfuse/sshfs years ago. Future development will continue there.
