### ISSUE TITLE
How to uninstall SSHFS from mac os

### ISSUE THREAD

**Issue by kamel1239** [osxfuse/sshfs#81]
After installing sshfs from https://osxfuse.github.io/ I would like to uninstall it properly.

is there any script or uninstaller to do the job ? Thanks.

**Comment by sMtzDczDq** [comment]
You can try this. https://www.mothersruin.com/software/SuspiciousPackage/  You load the pkg in it and it shows files it the installs. Then you can delete them manually. 
https://www.corecode.io/uninstallpkg/ this is more like an uninstaller but a bit overkill. There are only 2 files in the installer package.

**Comment by Rivers47** [comment]
All you need to do is to remove '/usr/local/bin/sshfs' and '/usr/local/share/man/man1/sshfs.1'
