### ISSUE TITLE
Licence doesn't have be agreed to in order to use.

### ISSUE THREAD

**Issue by danwdart** [osxfuse/sshfs#84]
<img width="617" alt="Screenshot 2023-12-11 at 09 43 43" src="https://github.com/osxfuse/sshfs/assets/334257/0ae65308-6490-4b8b-8f0e-af58f32a83b9">

One does not have to accept the GPL to use things licenced under it. One only has to use the GPL to _distribute_ them.

**Comment by bfleischer** [comment]
This is the easiest way to make the user aware of the license. "Accepting" the GPL might not be a legal requirement for installing the software, but it doesn't hurt either.
